mdbx writemap flag
erigontech/erigon pull request #11238
Opened 2024-07-19 10:12 UTC by JkLondon

close #11203

2024-07-19 10:18 UTC, AskAlexSharov requested changes

2024-07-19 10:18 UTC, AskAlexSharov commented on cmd/utils/flags.go
> +	TxPoolMdbxWriteMapFlag = cli.BoolFlag{
let's don't add more flags

2024-07-24 02:39 UTC, AskAlexSharov commented
let's use existing --db.writemap flag

2024-07-28 11:56 UTC, JkLondon commented on cmd/utils/flags.go
> +	TxPoolMdbxWriteMapFlag = cli.BoolFlag{
resolved

2024-07-29 02:16 UTC, AskAlexSharov approved these changes

2024-07-29 02:17 UTC, merged