added custom genesis file path flag to e3 client
erigontech/erigon pull request #11550
Opened 2024-08-09 16:03 UTC by JkLondon

closes #11462

2024-08-12 11:36 UTC, AskAlexSharov requested changes
I’m not sure it’s right solution. Why geth doesn’t need this flag?

2024-08-21 09:52 UTC, JkLondon commented
waiting until hive tests would be fixed (the rest is OK)

2024-08-23 12:11 UTC, yperbasis approved these changes

2024-08-23 13:06 UTC, AskAlexSharov approved these changes

2024-08-23 13:06 UTC, merged