compression: additional limit for effective dict
erigontech/erigon pull request #12087
Opened 2024-09-25 10:33 UTC by stevemilk

#11921

2024-09-27 09:19 UTC, AskAlexSharov requested changes

2024-09-27 09:19 UTC, AskAlexSharov commented on erigon-lib/seg/parallel_compress.go
> +			continue
jump outside of mutex section - it's deadlock

2024-09-27 13:29 UTC, stevemilk commented
MaxDictPatterns = MaxDictPatterns * 2
EffectiveDictLimit = MaxDictPatterns / 2 

With above config, init-dict will include more patterns than before, and may exclude some high-score patterns during dict reduction because patterns are hit randomly, low-score pattern may occupy the space of effective dict in advance.

will re-consider the solution.

2024-09-30 08:34 UTC, stevemilk commented
The previous version incorrectly included some unused patterns
I'v updated , however, the compression ratio will still be impacted to some extent.

Here's the reason:
In the current design, init-dict is reduced to reduced-dict after compression, retaining only the used patterns. For example, if len(init-dict) = 1024 and len(reduced-dict) = 512, with a compression ratio of 0.3, setting effectiveDictLimit to 512 keeps the ratio the same. However, if effectiveDictLimit is less than len(reduced-dict), some patterns will be dropped, potentially increasing the compression ratio.

I believe effectiveDictLimit serves as a hard limit to prevent the resulting dictionary from becoming too large, rather than a means to improve the compression ratio. I conducted some investigation but would appreciate your insights or suggestions for a better solution. @AskAlexSharov

2024-09-30 09:48 UTC, AskAlexSharov commented
Tnx. I will trst another day

2025-05-25 03:29 UTC, AskAlexSharov commented
Closing due to no activity

2025-05-25 03:29 UTC, closed without merging