Update BLS library
erigontech/erigon pull request #12288
Opened 2024-10-12 10:53 UTC by Giulio2002

2024-10-12 16:32 UTC, AskAlexSharov requested changes

2024-10-12 16:32 UTC, AskAlexSharov commented on go.mod
> +go 1.23
probably this change not related to PR?

2024-10-13 10:35 UTC, AskAlexSharov commented
FYI: it solves the problem

2024-10-13 17:43 UTC, Giulio2002 commented on go.mod
> +go 1.23
I think the toolchain is tho

2024-10-13 17:44 UTC, Giulio2002 commented
fixes https://github.com/erigontech/erigon/issues/12287

2024-10-13 17:53 UTC, Giulio2002 commented on go.mod
> +go 1.23
actually no, it does not :)

2024-10-16 04:24 UTC, AskAlexSharov approved these changes

2024-10-16 04:24 UTC, merged