Do not cancel in progress jobs in case of 'main' branch.
erigontech/erigon pull request #12296
Opened 2024-10-14 07:50 UTC by lystopad

See https://github.com/erigontech/erigon/issues/12125

2024-10-14 09:10 UTC, michelemodolo approved these changes

2024-10-14 09:45 UTC, lystopad commented
@AskAlexSharov , hi
please, feel free to merge it after review if you have no objections.

2024-10-15 04:40 UTC, shohamc1 commented
I think we should add `release/*` in addition to `main`

2024-10-15 04:47 UTC, shohamc1 requested changes
Please rebase your changes on `main` instead of my branch

2024-10-15 10:38 UTC, shohamc1 approved these changes

2024-10-15 12:48 UTC, AskAlexSharov approved these changes

2024-10-16 03:31 UTC, merged