fix race for global vars
erigontech/erigon pull request #12512
Opened 2024-10-28 07:08 UTC by shotasilagadze

2024-10-28 07:16 UTC, AskAlexSharov commented on cl/phase1/network/services/batch_signature_verification.go
> +	batchCheckInterval          = int64(500)
can use `atomic.Int64` or `atomic.Pointer[time.Duration]`

2024-10-28 14:33 UTC, Giulio2002 requested changes

2024-10-28 14:33 UTC, Giulio2002 commented on cl/phase1/network/services/batch_signature_verification.go
> +	batchCheckInterval.Store(500)
????

2024-10-28 14:33 UTC, Giulio2002 commented on cl/phase1/network/services/batch_signature_verification.go
> +	ticker := time.NewTicker(time.Duration(batchCheckInterval.Load()) * time.Millisecond)
this is likely wrong why are you atomicizing a constant?

2024-10-28 14:33 UTC, Giulio2002 commented on cl/sentinel/gossip.go
> +	iterationInterval := time.NewTicker(10000 * time.Millisecond)
why?

2024-10-28 14:33 UTC, Giulio2002 commented on cl/merkle_tree/merkle_tree.go
> +	m.mu.Lock()
plz test performance impact on `ProcessEpoch`

2024-10-28 14:33 UTC, Giulio2002 commented on cl/phase1/network/services/attestation_service_test.go
> +	batchCheckInterval.Store(1)
why?

2024-10-28 14:33 UTC, Giulio2002 commented
Btw - concurrent read is not a "race" - i think you are atomicizing way too much

2024-10-28 14:34 UTC, Giulio2002 requested changes

2024-10-28 14:34 UTC, Giulio2002 commented on cl/beacon/handler/config.go
> +	for currentVersion, entry := range forkVersionSchedule {
this is called once at startup... how does this cause a race?

2024-10-28 14:34 UTC, Giulio2002 commented on cl/clparams/config.go
> +	ForkVersionSchedule atomic.Pointer[map[libcommon.Bytes4]VersionScheduleEntry] `json:"-"` // Schedule of fork epochs by version.
this is updated once at startup... how does this cause a race?

2024-10-28 14:34 UTC, Giulio2002 commented on cl/clparams/config.go
>  func configForkSchedule(b *BeaconChainConfig) map[libcommon.Bytes4]VersionScheduleEntry {
this is called once at startup... how does this cause a race?

2024-10-28 14:34 UTC, Giulio2002 commented on cl/clparams/config.go
>  func (b *BeaconChainConfig) InitializeForkSchedule() {
this is called once at startup... how does this cause a race?

2024-10-28 17:03 UTC, Giulio2002 commented on cl/phase1/network/services/batch_signature_verification.go
> +	batchCheckInterval.Store(500)
yeah no keep this as normal - i am definetely not doing this just for a race warn

2024-10-28 17:03 UTC, Giulio2002 commented on cl/phase1/network/services/batch_signature_verification.go
> +	ticker := time.NewTicker(time.Duration(batchCheckInterval.Load()) * time.Millisecond)
yeah no keep this as normal - i am definetely not doing this just for a race warn

2024-10-29 19:42 UTC, domiwei commented
I suggest to move `BatchSignatureVerifier` out of services pkg and mock it.

2024-10-29 22:12 UTC, Giulio2002 approved these changes

2024-10-29 22:12 UTC, merged