docs: removed a non-existent section from the README
erigontech/erigon pull request #12762
Opened 2024-11-18 23:49 UTC by shashiyy

I removed the section titled '#blocks-execution-is-slow-on-cloud-network-drives' from the README because the title did not exist. This action is called 'cleaning up invalid or erroneous content'

2024-11-19 02:59 UTC, AskAlexSharov approved these changes

2024-11-19 03:02 UTC, AskAlexSharov requested changes
https://github.com/erigontech/erigon?tab=readme-ov-file#cloud-network-drives

2024-11-19 10:59 UTC, shashiyy commented
> https://github.com/erigontech/erigon?tab=readme-ov-file#cloud-network-drives

@AskAlexSharov  fixed

2024-11-21 02:48 UTC, AskAlexSharov approved these changes

2024-11-21 02:48 UTC, merged