cache tx granularity
erigontech/erigon pull request #13134
Opened 2024-12-16 18:12 UTC by JkLondon

closes #13088
Not really sure about 2 caches conception but like it

2024-12-17 03:06 UTC, AskAlexSharov requested changes

2024-12-17 03:06 UTC, AskAlexSharov commented on turbo/jsonrpc/receipts/receipts_generator.go
> +	if receipt, ok := g.receiptCache.Get(txNum); ok {
`txNum` is not reorg-resistant

2024-12-17 12:56 UTC, JkLondon commented on turbo/jsonrpc/receipts/receipts_generator.go
> +	if receipt, ok := g.receiptCache.Get(txNum); ok {
done

2024-12-18 07:18 UTC, AskAlexSharov approved these changes

2024-12-18 07:18 UTC, merged